require_relative "../lib/game_content"
require 'tempfile'

# Validate and stage the complete bilingual set before replacing any output.
# Keep rollback copies until all three replacements have succeeded.
module GameRoomTabooBuild
  def self.commit(outputs)
    temporary, prepared, installed = [], [], []
    preserve = false
    begin
      outputs.each do |path, bytes|
        stage = Tempfile.create(['.taboo-stage-', '.rb'], File.dirname(path))
        temporary << stage
        stage.binmode
        stage.write(bytes.encode('UTF-8'))
        stage.close
        backup = nil
        if File.exist?(path)
          backup = Tempfile.create(['.taboo-backup-', '.rb'], File.dirname(path))
          temporary << backup
          backup.binmode
          backup.write(File.binread(path))
          backup.close
        end
        prepared << [path, stage, backup]
      end
      prepared.each do |path, stage, backup|
        File.rename(stage.path, path)
        installed << [path, backup]
      end
    rescue StandardError => error
      failures = []
      installed.reverse_each do |path, backup|
        begin
          backup ? File.rename(backup.path, path) : File.unlink(path)
        rescue StandardError => rollback_error
          failures << "#{path}: #{rollback_error.class}"
        end
      end
      raise error if failures.empty?
      preserve = true
      raise IOError, "Taboo output rollback failed: #{failures.join('; ')}. Recovery files: #{temporary.map(&:path).join(', ')}"
    ensure
      temporary.each do |file|
        file.close unless file.closed?
        File.unlink(file.path) if !preserve && File.exist?(file.path)
      end
    end
  end
end

root = File.expand_path("../content", __dir__)
rows = File.readlines(File.join(root,"taboo_editorial.txt"), encoding: "UTF-8").map(&:strip).reject { |line| line.empty? || line.start_with?("#") }
raise "Expected exactly 500 edited bilingual rows" unless rows.length == 500
rows.each_with_index do |line,index|
  fields = line.split("|",-1)
  raise "Bad row #{index+1}" unless fields.length == 4
  [0,2].each do |start|
    word, forbidden = fields[start], fields[start+1].split(";",-1)
    raise "Incomplete card #{index+1}" unless forbidden.length == 5 && ([word]+forbidden).all? { |s| !s.empty? && s == s.strip }
    raise "Repeated restriction #{index+1}" unless forbidden.map(&:downcase).uniq.length == 5
    raise "Target as restriction #{index+1}" if forbidden.any? { |s| s.downcase == word.downcase }
  end
end
metadata = []
outputs = {}
[["pl-PL",0,"PL"],["en",2,"EN"]].each do |language,start,suffix|
  data = rows.each_with_index.map do |row,index|
    fields = row.split("|")
    { "id" => "taboo.#{language.downcase}.#{format('%03d',index+1)}", "word" => fields[start], "forbidden" => fields[start+1].split(";"), "source" => "Game Room editorial, 2026-09-17" }
  end
  raise "Duplicate targets #{language}" unless data.map { |e| e["word"].downcase }.uniq.length == 500
  pack = GameRoomContent::Pack.new(id: "taboo.general.#{language.downcase}.v1",set_id: "taboo.general",kind: "taboo_cards",language_id: language,
    version: 1,title: "General",game_ids: ["taboo"],author: "Game Room editorial",license: "GPL-3.0-or-later",entry_count: 500,data: data)
  name = "taboo_cards_#{suffix.downcase}_data"
  outputs[File.join(root,"#{name}.rb")] = "# encoding: UTF-8\n# Generated from taboo_editorial.txt; see TABOO_CONTENT_NOTICE.md.\nrequire 'json'\nmodule GameRoomContent::Taboo#{suffix}\n  def self.load\n    JSON.parse(<<'CARDS_#{pack.checksum}')\n#{JSON.generate(data)}\nCARDS_#{pack.checksum}\n  end\nend\n"
  metadata << { language: language, suffix: suffix, name: name, checksum: pack.checksum }
end
body = "# encoding: UTF-8\n# Generated by tools/build-taboo-cards.rb.\nrequire_relative '../lib/game_content'\n"
metadata.each do |m|
  body << "module GameRoomContent::Taboo#{m[:suffix]}; end\nGameRoomContent.registry.register_pack(GameRoomContent::Pack.new(\n  id: #{"taboo.general.#{m[:language].downcase}.v1".inspect}, set_id: 'taboo.general', kind: 'taboo_cards',\n  language_id: #{m[:language].inspect}, version: 1, title: 'General', game_ids: ['taboo'],\n  author: 'Game Room editorial', license: 'GPL-3.0-or-later', entry_count: 500,\n  checksum: #{m[:checksum].inspect},\n  loader: -> { require_relative #{m[:name].inspect}; GameRoomContent::Taboo#{m[:suffix]}.load }\n))\n"
end
outputs[File.join(root,"taboo_cards.rb")] = body
GameRoomTabooBuild.commit(outputs)
puts JSON.pretty_generate(metadata)
